# This is a basic workflow to help you get started with Actions

name: Test & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '**.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '**.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureCloud'
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

          for file in $( git diff-tree --no-commit-id --name-only -r ${{ github.sha }} )
          do
            if [[ "$file" == *.sh ]]
            then
              let "randomIdentifier=$RANDOM*$RANDOM"
              export RESOURCE_GROUP="test-deploy-rg-$randomIdentifier"
              
              echo "Running $file ..."
              chmod +X $file
              /bin/bash $file

              az group delete $RESOURCE_GROUP -y --no-wait
            fi
          done
